title: Introduction to Text Analysis
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/intro-text-analysis/\">View workshop content in GitHub</a>"
